apiVersion: v1
kind: Secret
metadata:
  name: airflow-custom-secrets
  namespace: airflow
type: Opaque
stringData:
  AIRFLOW__CORE__FERNET_KEY: "2aZmS9YFA65fsqwuuJnuBYPD012f-9Epng-6UcQK06M="
  AIRFLOW__WEBSERVER__SECRET_KEY: "f5b5b15f0b4952907adc89d907c90eeb5da90bbfd779e0f83447c78e67e88abf"
